
hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

custom_reward_function:
  reward_kwargs:
    compute_reward: compute_reward_relu
    text_weight: 1.0
    distinctiveness_weight: 100.0
    length_penalty_max_tokens: 1024

algorithm:
  use_personality_diversity: true
  personality_domain: general

data:
  train_files: 
  val_files: 
  apply_chat_template_kwargs:
    enable_thinking: true


